movies_dat: ../data/ml-1m/movies.dat
movies_csv: ../data/ml-1m/movies.csv
ratings_dat: ../data/ml-1m/ratings.dat
ratings_csv: ../data/ml-1m/ratings.csv
users_file: ../data/ml-1m/users.dat
NMF:
  n_components: 5
factorised_users_file: ../data/ml-1m/factorised_users_file.txt
factorised_movies_file: ../data/ml-1m/factorised_movies_file.txt
factorised_diag_file: ../data/ml-1m/factorised_diag_file.txt
MovieID_and_row_file: ../data/ml-1m/MovieID_and_row.csv
factorised_users_py: ../data/ml-1m/factorised_users_file.py
factorised_movies_py: ../data/ml-1m/factorised_movies_file.py
factorised_diag_py: ../data/ml-1m/factorised_diag_file.py
MovieIE_and_row_py: ../data/ml-1m/MovieID_and_row.py
